### ISSUE TITLE
Scritte buggate

### ISSUE THREAD

**Issue by heryoff** [gabelluardo/anime-dl#103]
Volevo solo dirti che le scritte utilizzandolo da windows sono abbastanza buggate, per il resto un bel tool.
Ah volevo chiedere anche quale archivio utilizzasi per scaricarli?

**Comment by gabelluardo** [comment]
@heryoff era un bug nel parsing dell'url, dalla prossima versione dovrebbe essere risolto, come archivio per adesso solo animeword
