### ISSUE TITLE
Subs are in italian

### ISSUE THREAD

**Issue by Iru21** [gabelluardo/anime-dl#79]
why
at least say it in the readme

**Comment by gabelluardo** [comment]
Sorry, you're right. When I started I planned to add an english archive too, but then I focused on other features used by me and other italian friends of mine. 
If you find an archive that saves episodes with the format `domain.tld/.../anime_name_xx.mp4` (where xx is the episode number) I think it would be easy to add an eng/other one, but maintaining it could be frustrating. 

For now, I'll only specify it on the readme.
\
\
\
p.s. team Roxy here :hand:
